name: flutter_readhub
description: A new Flutter Readhub application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.2.6+1010

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.3
  #  国际化支持
  flutter_localizations:
    sdk: flutter
  # 状态管理State
  provider: ^5.0.0
  #  吐司toast
  bot_toast: ^4.0.1
  #  设备信息
  device_info_plus: ^1.0.1
  #  应用包信息
  package_info_plus: ^1.0.1

  # WebView
  webview_flutter: ^2.0.4
  flutter_webview_plugin: ^0.4.0
  #  网络请求相关dio
  dio: ^4.0.0
  #  加载网络图片
  cached_network_image: ^3.0.0
  synchronized: ^3.0.0
  #  下拉刷新
  pull_to_refresh: ^2.0.0
  #  本地缓存sp
  shared_preferences: ^2.0.5
  #用于做骨架屏-闪光效果
  shimmer: ^2.0.0
  #跳转系统浏览器/打电话等
  url_launcher: ^6.0.3
  #二维码-生成
  qr_flutter: ^4.0.0
  #工具类
  flustars: ^2.0.1
  #动态权限申请-8.0.0版本需在Profile申请需要启用的权限 https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler/example/ios/Podfile
  permission_handler: ^8.0.0+1
  #文件路径
  path_provider: ^2.0.1
  #分享文字及文件-注意保存文件位置
  #注意0.1.2以后的版本分享图片微信提示获取资源失败，分享到其它平台正常
  #  flutter_share_plugin: 0.1.2
  #  share: ^2.0.1
  # 使用官网分支增加分享特定App/App某个方法 增加判断App是否安装方法-Android
  # 参考官网 https://flutter.dev/docs/development/packages-and-plugins/using-packages
  share:
    git:
      url: git://github.com/AriesHoo/plugins.git
      path: packages/share
      ref: master
  #  mac分享才有意义web及windows无意义shareFile方法都没有实现shareText也是调用的url_launcher
  share_plus: ^2.1.2
  #  自适应断点？---响应式
  adaptive_breakpoints: ^0.0.4
  #  desktop窗口控制
  desktop_window: ^0.4.0
  #  macos webView
  flutter_macos_webview:
    path: ./plugins/flutter_macos_webview
dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  fonts:
    - family: iconfont
      fonts:
        - asset: assets/fonts/iconfont.ttf
  assets:
    - assets/images/
    - assets/images/share/
  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
flutter_intl:
  enabled: true
